

============================== 2023-08-15 09:30:13.203882 | e247b515-0244-47f0-b255-c8e93859bb51 ==============================
[0m09:30:13.203882 [info ] [MainThread]: Running with dbt=1.4.7
[0m09:30:13.203882 [debug] [MainThread]: running dbt with arguments {'write_json': True, 'use_colors': True, 'printer_width': 80, 'version_check': True, 'partial_parse': True, 'static_parser': True, 'profiles_dir': 'C:\\Users\\thuyh\\.dbt', 'send_anonymous_usage_stats': True, 'quiet': False, 'no_print': False, 'cache_selected_only': False, 'skip_profile_setup': False, 'which': 'init', 'indirect_selection': 'eager'}
[0m09:30:13.203882 [debug] [MainThread]: Tracking: tracking
[0m09:30:13.235131 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216BA01FB50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216B9DF68D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216BA0AC250>]}
[0m09:30:22.251184 [debug] [MainThread]: Starter project path: C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\include\starter_project
[0m09:30:31.800309 [debug] [MainThread]: Traceback (most recent call last):
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\factory.py", line 57, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\snowflake\__init__.py", line 4, in <module>
    from dbt.adapters.snowflake.relation import SnowflakeRelation  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\snowflake\relation.py", line 5, in <module>
    from dbt.adapters.relation_configs import RelationConfigChangeAction, RelationResults
ModuleNotFoundError: No module named 'dbt.adapters.relation_configs'

[0m09:30:31.800309 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216BB1926D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216BB192710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000216BB192750>]}
[0m09:30:31.800309 [debug] [MainThread]: Flushing usage events
[0m09:30:33.330068 [error] [MainThread]: Encountered an error:
No module named 'dbt.adapters.relation_configs'
[0m09:30:33.353279 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\main.py", line 136, in main
    results, succeeded = handle_and_check(args)
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\main.py", line 253, in run_from_args
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 305, in run
    self.create_profile_from_target(adapter, profile_name=project_name)
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\task\init.py", line 173, in create_profile_from_target
    load_plugin(adapter)
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\factory.py", line 202, in load_plugin
    return FACTORY.load_plugin(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\factory.py", line 57, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\snowflake\__init__.py", line 4, in <module>
    from dbt.adapters.snowflake.relation import SnowflakeRelation  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thuyh\AppData\Local\Programs\Python\Python311\Lib\site-packages\dbt\adapters\snowflake\relation.py", line 5, in <module>
    from dbt.adapters.relation_configs import RelationConfigChangeAction, RelationResults
ModuleNotFoundError: No module named 'dbt.adapters.relation_configs'

